image:     
    name: amazon/aws-cli
    entrypoint: [""]

stages:
    - build

build:
    stage: build
    variables:
        SERVICES: s3:4572
        HOSTNAME_EXTERNAL: localstack 
        DEFAULT_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: localkey
        AWS_SECRET_ACCESS_KEY: localsecret
    services:
        - name: localstack/localstack
          alias: localstack
    script:
        - curl localstack:4566
