image: docker:stable
stages:
  - build

build:
  stage: build
  parallel:
    matrix:
      - ARCH: ["amd64", "arm64"]
        ARCH_ALT: ["x86_64", "arm64"]
  script:
    - echo ${ARCH}
    - echo ${ARCH_ALT}
