image: docker:stable
stages:
  - build

build:
  stage: build
  services:
    - name: hashicorp/terraform:1.0.0
      alias: terraform
      entrypoint:
        - ""
  script:
    - terraform --version
