image: docker:stable
stages:
  - build

build:
  stage: build
  parallel:
    matrix:
      - ARCH: ["amd64"]
        ARCH_ALT: ["x86_64"]
        SERVER: ["dind"]
      - ARCH: ["arm64"]
        ARCH_ALT: ["arm64"]
        SERVER: ["graviton-dind"]
  script:
    - echo ${ARCH}
    - echo ${ARCH_ALT}
  tags:
    - ${TAGS}
