image:
  name: felipefrizzo/packer:latest
  entrypoint: 
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - build

build:
  stage: build
  script:
    - ls -lha
    - packer --version
    - packer init mongodb.pkr.hcl
    - ls -lha
    - /usr/bin/packer validate mongodb.pkr.hcl
