image: docker:stable
stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  stage: build
  tags: [ gitlab-org-docker ]
  services:
    - docker:dind
  script:
    - env
