image:
  name: felipefrizzo/packer:latest
  entrypoint: [""]

stages:
  - build

build:
  stage: build
  script:
    - ls -lha
    - packer init mongodb.pkr.hcl
    - ls -lha
    - packer validate mongodb.pkr.hcl
