image:
  name: hashicorp/packer:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


stages:
  - build

build:
  stage: build
  script:
    - ls -lha
    - packer --version
    - packer validate mongodb.pkr.hcl
