image: golang:1.17

stages:
    - build

build:
    stage: build
    variables:
        SERVICES: s3
        HOSTNAME_EXTERNAL: localstack 
        DEFAULT_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: localkey
        AWS_SECRET_ACCESS_KEY: localsecret
    services:
        - name: localstack/localstack
          alias: localstack
    script:
        - go mod download
        - go run main.go
