image:
  name: hashicorp/packer:1.7.3
  entrypoint: 
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - build

build:
  stage: build
  script:
    - ls -lha
    - packer --version
    - packer init mongodb.pkr.hcl
    - ls -lha
    - packer validate mongodb.pkr.hcl
